### ISSUE TITLE
... 'TwilioSyncClient.framework' was built for iOS + iOS Simulator

### ISSUE THREAD

**Issue by wadewegner** [twilio/twilio-sync-ios#2]
When following the Carthage instructions [here](https://www.twilio.com/docs/sync/sync-sdk-download#completing-framework-integration) I get the error:

```
/Users/wwegner/Projects/ClipSynk/ClipSynk.xcodeproj Building for iOS Simulator, but the linked and embedded framework 'TwilioSyncClient.framework' was built for iOS + iOS Simulator.
```

I don't have a lot of experience with either Xcode or Carthage, but [this response](https://developer.apple.com/forums/thread/669411?answerId=652663022#652663022) suggested that perhaps the framework would require an update.

**Comment by Gray-Wind** [comment]
Thank you for heads up, we will re-prioritize work on XCFramework and we will start working on it as soon as possible.

**Comment by Gray-Wind** [comment]
XCFramework support has been released!
