### ISSUE TITLE
Latest SDK version doesn't call onDocument updated

### ISSUE THREAD

**Issue by sammyfdm** [twilio/twilio-sync-ios#4]
When I setup my TwilioSync Document on version `0.8.7` the `onDocument(_ document: TWSDocument, updated data: [String: Any], eventContext: TWSEventContext)` is successfully called when another platform publishes changes to the document. However when I updated to `1.2.1` it no longer calls this function. I made no changes to the code for creating/opening documents (the only changes I made were for unrelated function calls that got renamed, e.g. `isSuccessful()` --> `isSuccessful`

Here's an example of one of the documents being opened:
```
if let options = TWSOpenOptions.open(withSidOrUniqueName: documentId) {
            syncClient?.openDocument(with: options, delegate: self, completion: { [weak self] (result, document) in
             ...
            })
}
```
Note that I can successfully write to the Document; it's just this delegate callback that's not happening.

**Comment by Gray-Wind** [comment]
We have just released 2.0 version, could you check please one again?

**Comment by Gray-Wind** [comment]
This change is the part of breaking release (bump from 0.* to 1.*).
You need to update your delegate method from

```swift
func onDocument(_ document: TWSDocument, updated data: [String: Any], eventContext: TWSEventContext)
```

to

```swift
func onDocument(_ document: TWSDocument, updated data: [String : Any], previousData: [String : Any], eventContext: TWSEventContext)
```

These changes were mentioned in the [release notes](https://www.twilio.com/docs/sync/ios/changelog#sync-sdk-for-ios-v100-january-19-2021) of the breaking release.

Feel free to open a new ticket if you face any more issues.

**Comment by sammyfdm** [comment]
Apologies, I've updated to v2.0 and changed which function signature I'm using and it appears to be working just fine now. Thanks for the help!
